### ISSUE TITLE
Concurrent Error

### ISSUE THREAD

**Issue by GershonR** [hsyyid/SimpleVotifierListener#5]
```
27.07 18:14:35 [Server] pool-2-thread-1/INFO [VotifierListener]: Test just voted and got a reward! You can too with /vote
27.07 18:14:35 [Server] pool-2-thread-1/INFO [io.github.hsyyid.essentialcmds]: [Server] executed command minecraft:give Test minecraft:cake 5
27.07 18:14:35 [Server] pool-2-thread-1/INFO [STDERR]: [java.lang.Thread:dumpStack:1329]: java.lang.Exception: Stack trace
27.07 18:14:35 [Server] pool-2-thread-1/INFO [STDERR]: [java.lang.Thread:dumpStack:1329]:   at java.lang.Thread.dumpStack(Thread.java:1329)
27.07 18:14:35 [Server] pool-2-thread-1/INFO [STDERR]: [java.lang.Thread:dumpStack:1329]:   at net.minecraft.entity.EntityTracker.handler$onAddEntityToTracker$0(EntityTracker.java:56)
27.07 18:14:35 [Server] pool-2-thread-1/INFO [STDERR]: [java.lang.Thread:dumpStack:1329]:   at net.minecraft.entity.EntityTracker.func_72785_a(EntityTracker.java)
27.07 18:14:35 [Server] pool-2-thread-1/INFO [STDERR]: [java.lang.Thread:dumpStack:1329]:   at net.minecraft.entity.EntityTracker.func_72786_a(EntityTracker.java:120)
27.07 18:14:35 [Server] pool-2-thread-1/INFO [STDERR]: [java.lang.Thread:dumpStack:1329]:   at net.minecraft.world.WorldManager.func_72703_a(SourceFile:30)
27.07 18:14:35 [Server] pool-2-thread-1/INFO [STDERR]: [java.lang.Thread:dumpStack:1329]:   at net.minecraft.world.World.func_72923_a(World.java:1135)
27.07 18:14:35 [Server] pool-2-thread-1/INFO [STDERR]: [java.lang.Thread:dumpStack:1329]:   at net.minecraft.world.WorldServer.func_72923_a(WorldServer.java:945)
27.07 18:14:35 [Server] pool-2-thread-1/INFO [STDERR]: [java.lang.Thread:dumpStack:1329]:   at net.minecraft.world.World.func_72838_d(World.java:1126)
27.07 18:14:35 [Server] pool-2-thread-1/INFO [STDERR]: [java.lang.Thread:dumpStack:1329]:   at org.spongepowered.common.SpongeImplHooks.onPlayerToss(SpongeImplHooks.java:163)
27.07 18:14:35 [Server] pool-2-thread-1/INFO [STDERR]: [java.lang.Thread:dumpStack:1329]:   at net.minecraft.entity.player.EntityPlayer.func_71019_a(EntityPlayer.java:349)
27.07 18:14:35 [Server] pool-2-thread-1/INFO [STDERR]: [java.lang.Thread:dumpStack:1329]:   at net.minecraft.command.CommandGive.func_71515_b(SourceFile:64)
27.07 18:14:35 [Server] pool-2-thread-1/INFO [STDERR]: [java.lang.Thread:dumpStack:1329]:   at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:100)
27.07 18:14:35 [Server] pool-2-thread-1/INFO [STDERR]: [java.lang.Thread:dumpStack:1329]:   at org.spongepowered.common.command.MinecraftCommandWrapper.tryExecute(MinecraftCommandWrapper.java:141)
27.07 18:14:35 [Server] pool-2-thread-1/INFO [STDERR]: [java.lang.Thread:dumpStack:1329]:   at org.spongepowered.common.command.MinecraftCommandWrapper.process(MinecraftCommandWrapper.java:127)
27.07 18:14:35 [Server] pool-2-thread-1/INFO [STDERR]: [java.lang.Thread:dumpStack:1329]:   at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:331)
27.07 18:14:35 [Server] pool-2-thread-1/INFO [STDERR]: [java.lang.Thread:dumpStack:1329]:   at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:279)
27.07 18:14:35 [Server] pool-2-thread-1/INFO [STDERR]: [java.lang.Thread:dumpStack:1329]:   at io.github.hsyyid.votifierlistener.VotifierListenerPlugin.onVote(VotifierListenerPlugin.java:217)
27.07 18:14:35 [Server] pool-2-thread-1/INFO [STDERR]: [java.lang.Thread:dumpStack:1329]:   at org.spongepowered.common.event.listener.VotifierEventListener_VotifierListenerPlugin_onVote55.handle(Unknown Source)
27.07 18:14:35 [Server] pool-2-thread-1/INFO [STDERR]: [java.lang.Thread:dumpStack:1329]:   at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95)
27.07 18:14:35 [Server] pool-2-thread-1/INFO [STDERR]: [java.lang.Thread:dumpStack:1329]:   at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:201)
27.07 18:14:35 [Server] pool-2-thread-1/INFO [STDERR]: [java.lang.Thread:dumpStack:1329]:   at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:242)
27.07 18:14:35 [Server] pool-2-thread-1/INFO [STDERR]: [java.lang.Thread:dumpStack:1329]:   at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:214)
27.07 18:14:35 [Server] pool-2-thread-1/INFO [STDERR]: [java.lang.Thread:dumpStack:1329]:   at com.vexsoftware.votifier.sponge.VotifierPlugin$3.run(VotifierPlugin.java:356)
27.07 18:14:35 [Server] pool-2-thread-1/INFO [STDERR]: [java.lang.Thread:dumpStack:1329]:   at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:138)
27.07 18:14:35 [Server] pool-2-thread-1/INFO [STDERR]: [java.lang.Thread:dumpStack:1329]:   at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:177)
27.07 18:14:35 [Server] pool-2-thread-1/INFO [STDERR]: [java.lang.Thread:dumpStack:1329]:   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
27.07 18:14:35 [Server] pool-2-thread-1/INFO [STDERR]: [java.lang.Thread:dumpStack:1329]:   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
27.07 18:14:35 [Server] pool-2-thread-1/INFO [STDERR]: [java.lang.Thread:dumpStack:1329]:   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
27.07 18:14:35 [Server] pool-2-thread-1/INFO [STDERR]: [java.lang.Thread:dumpStack:1329]:   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
27.07 18:14:35 [Server] pool-2-thread-1/INFO [STDERR]: [java.lang.Thread:dumpStack:1329]:   at java.lang.Thread.run(Thread.java:745)
27.07 18:14:35 [Server] pool-2-thread-1/ERROR [Sponge]: Detected attempt to add entity 'EntityItem['item.item.cake'/20761, l='world', x=775.31, y=79.32, z=-360.08]' to tracker asynchronously.
27.07 18:14:35 [Server] INFO This is very bad as it can cause ConcurrentModificationException's during a server tick.
27.07 18:14:35 [Server] INFO Skipping...
27.07 18:14:35 [Server] pool-2-thread-1/INFO Given [Cake] * 5 to Test
```

**Comment by hsyyid** [comment]
Seems to do with `/give` but I'll look into it

**Comment by GershonR** [comment]
Any news on fixing this?

```
08.09 19:55:01 [Server] pool-2-thread-1/INFO [VotifierListener]: herobrine876543 just voted and got a reward! You can too with /vote
08.09 19:55:01 [Server] pool-2-thread-1/INFO [io.github.hsyyid.essentialcmds]: [Server] executed command minecraft:give herobrine876543 minecraft:gold_ingot 5
08.09 19:55:01 [Server] pool-2-thread-1/INFO [STDERR]: [java.lang.Thread:dumpStack:1329]: java.lang.Exception: Stack trace
08.09 19:55:01 [Server] pool-2-thread-1/INFO [STDERR]: [java.lang.Thread:dumpStack:1329]:   at java.lang.Thread.dumpStack(Thread.java:1329)
08.09 19:55:01 [Server] pool-2-thread-1/INFO [STDERR]: [java.lang.Thread:dumpStack:1329]:   at net.minecraft.entity.EntityTracker.handler$onAddEntityToTracker$0(EntityTracker.java:56)
08.09 19:55:01 [Server] pool-2-thread-1/INFO [STDERR]: [java.lang.Thread:dumpStack:1329]:   at net.minecraft.entity.EntityTracker.func_72785_a(EntityTracker.java)
08.09 19:55:01 [Server] pool-2-thread-1/INFO [STDERR]: [java.lang.Thread:dumpStack:1329]:   at net.minecraft.entity.EntityTracker.func_72786_a(EntityTracker.java:120)
08.09 19:55:01 [Server] pool-2-thread-1/INFO [STDERR]: [java.lang.Thread:dumpStack:1329]:   at net.minecraft.world.WorldManager.func_72703_a(SourceFile:30)
08.09 19:55:01 [Server] pool-2-thread-1/INFO [STDERR]: [java.lang.Thread:dumpStack:1329]:   at net.minecraft.world.World.func_72923_a(World.java:1135)
08.09 19:55:01 [Server] pool-2-thread-1/INFO [STDERR]: [java.lang.Thread:dumpStack:1329]:   at net.minecraft.world.WorldServer.func_72923_a(WorldServer.java:945)
08.09 19:55:01 [Server] pool-2-thread-1/INFO [STDERR]: [java.lang.Thread:dumpStack:1329]:   at net.minecraft.world.World.func_72838_d(World.java:1126)
08.09 19:55:01 [Server] pool-2-thread-1/INFO [STDERR]: [java.lang.Thread:dumpStack:1329]:   at org.spongepowered.common.SpongeImplHooks.onPlayerToss(SpongeImplHooks.java:163)
08.09 19:55:01 [Server] pool-2-thread-1/INFO [STDERR]: [java.lang.Thread:dumpStack:1329]:   at net.minecraft.entity.player.EntityPlayer.func_71019_a(EntityPlayer.java:349)
08.09 19:55:01 [Server] pool-2-thread-1/INFO [STDERR]: [java.lang.Thread:dumpStack:1329]:   at net.minecraft.command.CommandGive.func_71515_b(SourceFile:72)
08.09 19:55:01 [Server] pool-2-thread-1/INFO [STDERR]: [java.lang.Thread:dumpStack:1329]:   at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:100)
08.09 19:55:01 [Server] pool-2-thread-1/INFO [STDERR]: [java.lang.Thread:dumpStack:1329]:   at org.spongepowered.common.command.MinecraftCommandWrapper.tryExecute(MinecraftCommandWrapper.java:141)
08.09 19:55:01 [Server] pool-2-thread-1/INFO [STDERR]: [java.lang.Thread:dumpStack:1329]:   at org.spongepowered.common.command.MinecraftCommandWrapper.process(MinecraftCommandWrapper.java:127)
08.09 19:55:01 [Server] pool-2-thread-1/INFO [STDERR]: [java.lang.Thread:dumpStack:1329]:   at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:331)
08.09 19:55:01 [Server] pool-2-thread-1/INFO [STDERR]: [java.lang.Thread:dumpStack:1329]:   at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:279)
08.09 19:55:01 [Server] pool-2-thread-1/INFO [STDERR]: [java.lang.Thread:dumpStack:1329]:   at io.github.hsyyid.votifierlistener.VotifierListenerPlugin.onVote(VotifierListenerPlugin.java:217)
08.09 19:55:01 [Server] pool-2-thread-1/INFO [STDERR]: [java.lang.Thread:dumpStack:1329]:   at org.spongepowered.common.event.listener.VotifierEventListener_VotifierListenerPlugin_onVote52.handle(Unknown Source)
08.09 19:55:01 [Server] pool-2-thread-1/INFO [STDERR]: [java.lang.Thread:dumpStack:1329]:   at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95)
08.09 19:55:01 [Server] pool-2-thread-1/INFO [STDERR]: [java.lang.Thread:dumpStack:1329]:   at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:201)
08.09 19:55:01 [Server] pool-2-thread-1/INFO [STDERR]: [java.lang.Thread:dumpStack:1329]:   at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:242)
08.09 19:55:01 [Server] pool-2-thread-1/INFO [STDERR]: [java.lang.Thread:dumpStack:1329]:   at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:214)
08.09 19:55:01 [Server] pool-2-thread-1/INFO [STDERR]: [java.lang.Thread:dumpStack:1329]:   at com.vexsoftware.votifier.sponge.VotifierPlugin$3.run(VotifierPlugin.java:356)
08.09 19:55:01 [Server] pool-2-thread-1/INFO [STDERR]: [java.lang.Thread:dumpStack:1329]:   at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:138)
08.09 19:55:01 [Server] pool-2-thread-1/INFO [STDERR]: [java.lang.Thread:dumpStack:1329]:   at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:177)
08.09 19:55:01 [Server] pool-2-thread-1/INFO [STDERR]: [java.lang.Thread:dumpStack:1329]:   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
08.09 19:55:01 [Server] pool-2-thread-1/INFO [STDERR]: [java.lang.Thread:dumpStack:1329]:   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
08.09 19:55:01 [Server] pool-2-thread-1/INFO [STDERR]: [java.lang.Thread:dumpStack:1329]:   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
08.09 19:55:01 [Server] pool-2-thread-1/INFO [STDERR]: [java.lang.Thread:dumpStack:1329]:   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
08.09 19:55:01 [Server] pool-2-thread-1/INFO [STDERR]: [java.lang.Thread:dumpStack:1329]:   at java.lang.Thread.run(Thread.java:745)
```

**Comment by dvhaldane** [comment]
I was able to resolve this by scheduling the give command as a synchronous event.

```
                    final String fcommand = command;

                    Scheduler scheduler = Sponge.getScheduler();
                    Task.Builder taskBuilder = scheduler.createTaskBuilder();

                    Task task = taskBuilder.execute(() -> Sponge.getCommandManager().process(Sponge.getServer().getConsole(), fcommand))
                            .delay(1, TimeUnit.MILLISECONDS).submit(votifierListenerPlugin);`
```

**Comment by GershonR** [comment]
Can you push a PR for it?
